title: All about me
author: Daniel Lew
email: dlew@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This site will be all about me

# social links
twitter_username: Nuuenkdaniel # DO NOT include the @ character, or else the build will fail!
github_username:  nuuenkdaniel # DO NOT include the @ character, or else the build will fail!
discord_username: Nuuenkdaniel

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
